### ISSUE TITLE
Show tags metadata the same way as it shows by default

### ISSUE THREAD

**Issue by meskill** [arnau/obsidian-metatable#1]
Hello, thanks for the plugin.

I want to ask to reuse default obsidian render for tags frontmatter as it provides best visuals, they are clickable and might be customized by themes.

For example:

without metatable plugin:
![image](https://user-images.githubusercontent.com/8974488/116889641-78829500-ac35-11eb-9bad-5a4cf91b2ecd.png)

with metatable plugin:
![image](https://user-images.githubusercontent.com/8974488/116889735-951ecd00-ac35-11eb-9ec2-fe2819c93369.png)

**Comment by arnau** [comment]
Hi @meskill thanks for reporting this. It is indeed a bug. The behaviour you are after works well when you use a frontmatter in the form of:

```yaml
tags:
  - foo
  - bar
---

But not if you do

```yaml
tags: foo, bar
```

Let me look into it.

**Comment by arnau** [comment]
Version [0.5.1](https://github.com/arnau/obsidian-metatable/releases/tag/0.5.1) fixes this issue. Thanks for reporting 👍
