### ISSUE TITLE
Feature Request: Exclude all fields except specific ones

### ISSUE THREAD

**Issue by LaP0573** [arnau/obsidian-metatable#10]
I know you can indicate the frontmatter fields you with to exclude from metatable, but I'd like a way to do the other way : exclude all by default and list the ones you want to exclude.

90% of my fields should be excluded as they are just metadata about the file and I don't want them showing up in presentation, only a few should show up (like a source field). Since I always add new types of fields, this requires me to constantly update the list of excluded fields which is not viable in the long term.

The ability to exclude all by default and specify which ones to whitelist would be great for that purpose 👌

**Comment by arnau** [comment]
Thanks for the suggestion, let me think about it

**Comment by arnau** [comment]
So, I changed the way you define settings such that you can choose the filter strategy. In your case you'll have to pick filter mode "keep" to exclude anything that is not in the list.

Available in 0.10.0.
