### ISSUE TITLE
Bug: Parent note metatable is duplicated on embedded notes

### ISSUE THREAD

**Issue by raddevon** [arnau/obsidian-metatable#12]
If I embed a note inside another note, the plugin appears to render another copy of the parent note's metatable inside the embedded note before that note's own metatable. Here's a screenshot to illustrate:

![image](https://user-images.githubusercontent.com/2027711/125698533-608bb2f5-6402-4354-b93a-feb50e9cbdd2.png)

**Comment by arnau** [comment]
Thanks for reporting, I'll take a look as soon as I can.

**Comment by arnau** [comment]
Hi @raddevon could you share here the minimal markdown (two files) that would help me reproduce this bug?

**Comment by raddevon** [comment]
Sorry for the delay, @arnau. I can no longer replicate this. Not sure what was happening there.

Thanks for the awesome plugin!

**Comment by arnau** [comment]
No worries! let me know if the error pops up again 👍

**Comment by TheLugal** [comment]
Hi there! It seems to me that the bug appears when one write on the line directly below the embed. Refreshing by changing to another document and back removes the duplicates.
![image](https://user-images.githubusercontent.com/1109057/141364718-fd32d7ea-dd79-4a77-aa20-34845eff9904.png)

I can upload the md-files, should you be unable to reproduce. I use obsidian-appimage v0.12.19 on linux kernel 5.14.16-zen1-1-zen

**Comment by arnau** [comment]
Hey @TheLugal , thanks for reporting! My hunch is that you are using `date updated` which contains a space and that is making Obsidian parse the frontmatter the wrong way. Mainly because spaces are not allowed in YAML keys.

If you do the test of changing the key to `date-updated`, does it change to the expected result?

**Comment by TheLugal** [comment]
Hi! I tried changing it to date-updated, but it didn't seem to work. I tried to set the key to "metatable-embed: true" on the embedded file, and "metatable-embed: false" on the "regular" file.
![122940](https://user-images.githubusercontent.com/1109057/141642237-b2093689-c9d4-4510-9fd0-d7e4168cbeef.png)
It looks like metatable tries to insert the frontmatter from the embedding file into the metatable of the embedded file.

**Comment by arnau** [comment]
Thanks for testing it @TheLugal 

Would it be ok for you to upload here the markdown files that can help me reproduce the problem.

**Comment by TheLugal** [comment]
Sure!
[Metatable-test.md](https://github.com/arnau/obsidian-metatable/files/7531964/Metatable-test.md)
[Metatable-test-embed.md](https://github.com/arnau/obsidian-metatable/files/7531965/Metatable-test-embed.md)

**Comment by arnau** [comment]
Thanks!

**Comment by arnau** [comment]
Hi @TheLugal, I'm afraid I can't reproduce the issue. With the two Markdown files you provided I get the following behaviour:

<img width="837" alt="Screenshot 2021-11-13 at 15 33 05" src="https://user-images.githubusercontent.com/33837/141649735-b114c94a-0ae0-44a9-953a-56dbbd3fe55d.png">

Could you provide some more information to narrow down where the issue may be coming from?

Mine are:

- Operating System: MacOS 11.6
- Obsidian: v0.12.19
- Community plugins:
  - Metatable v0.10.3
- Core plugins:
  - File Explorer
  - Search
  - Quick Switcher
  - Graph View
  - Backlinks
  - Page preview
  - Note composer
  - Command palette
  - Markdown format importer
  - Word count
  - Open in default app
  - File recovery

Which I _think_ is a default installation with just Metatable installed.

**Comment by arnau** [comment]
Nevermind, I finally got to reproduce the behaviour! This is progress :)

**Comment by arnau** [comment]
So, if I have narrowed it down properly the issue is as follows:

Given a file `a.md` that embeds file `b.md` using

```markdown
![[b.md]]
```

And setting up the workspace such that `a.md` is open twice, once in preview mode and once in edit mode.

Writing text straight after the embedding expression `![[b.md]]` triggers a rerender for the embedded preview that makes the metatable duplicate values.

However, writing text as a _new_ paragraph (i.e. two carriage returns) show the expected behaviour.

**Comment by arnau** [comment]
@TheLugal I released a new version, 0.10.4 which should fix this problem. Let me know if not, thanks!

**Comment by TheLugal** [comment]
Hi @arnau, your fix worked nicely! It was a small issue, but thank you for taking out of your time to fix it. :)
