### ISSUE TITLE
Using shortened links ?

### ISSUE THREAD

**Issue by Elaws** [arnau/obsidian-metatable#13]
Hi,

Is there a way to use shortened links in YAML frontmatter ? 

e.g. : 

`[LINK](URL)`

**Comment by arnau** [comment]
Hi @Elaws, 

The only options for adding links in YAML are the ones described here https://github.com/arnau/obsidian-metatable#autolinks
with the "autolinks" config option enabled.

**Comment by Elaws** [comment]
Thanks for your quick reply @arnau,

I indeed read this section and already enabled autolinks. Is there any plan to support such `[LINK](URL)` links ? 

More often than not, a reduced link is preferable, as a full link would take too much space in a dataview query for e.g.

Thanks

**Comment by arnau** [comment]
I had no plans to add the ability to parse markdown links. It has the same issue as obsidian links `[[link]]` where `[` and `]` are YAML reserved characters symbolising an array. So, in case of implementing this, it would require the yaml field to be defined as a String (same rules laid out for obsidian links).

All that said, once I have a bit of free time I can give it a go, unless you want to try? :)

**Comment by arnau** [comment]
This feature has been available for a while now.
