### ISSUE TITLE
Request: A better experience for filtering keys

### ISSUE THREAD

**Issue by OfficerHalf** [arnau/obsidian-metatable#17]
Right now the keys to filter are a single comma separated list. As soon as you have more than a couple, it's pretty difficult to manage. The input field is pretty small. It would be awesome to have them in a table or similar to be able to see them at a glance and add/remove them.

**Comment by arnau** [comment]
@OfficerHalf I just released version 0.11.0 which should improve a bit the experience of managing filter keys.
