### ISSUE TITLE
Make metatable appearance the similar to Obsidian's default metadata widget or add option to do that

### ISSUE THREAD

**Issue by bzimor** [arnau/obsidian-metatable#18]
I like your plugin and I use it instead of Obsidian's native widget, because native one doesn't support attributes other than tags and aliases.  I tried to do it using style snippets but it was impossible to do without modifying the actual plugin code. This is my version in theme Atom:
![image](https://user-images.githubusercontent.com/23069759/139813638-2a1ffd1e-f10a-4886-9045-67c87177630a.png)
However this modification works only in this theme and likely to break if you update your source code, so it would be cool if there is an option to make it similar to Obsidian's metadata.

**Comment by phlind** [comment]
@bzimor Could you share your css code? That looks really cool.

**Comment by bzimor** [comment]
@phlind, I achieved this not only with css snippet, but I had to modified this plugin's source code:
1) my css snippet: https://gist.github.com/bzimor/be4ae99f7d0abed5b262103cc18fba9d
2) modified main.js file: https://gist.github.com/bzimor/db50197132e069928cde1a96b8dc8c61

**Comment by arnau** [comment]
Thanks @bzimor , I'm considering your suggestion.

When I designed this plugin one of the biggest points for me was to create a widget that would sandbox itself from other CSS, so I used a shadowdom to that end.

In hindsight, not everyone is as worried as me with interference so something that I'm considering that could be introduced is a setting where you can choose a "naked version" with a "bring your own CSS" mindset.

**Comment by arnau** [comment]
@bzimor changes in `main` now add a setting `naked` which will just add the metatable structure without sandbox or CSS. Which means you can just drop your CSS as a CSS snippet (see `styles.css`) and it will give you complete control.

Let me know if you try it. I'm looking to release it as part of v0.11

**Comment by bzimor** [comment]
@arnau, thank you for considering my suggestion and adding `naked` version. I tried it, now it is easier to customize appearance.

**Comment by arnau** [comment]
Nice, thanks!
