### ISSUE TITLE
Clickable URL And Metadata Bug

### ISSUE THREAD

**Issue by EhuddR** [arnau/obsidian-metatable#2]
Hi! First of all thank you for this plugin. I would like to know if there is a possibility to make the metadata interactive links. For example in my notes I like to have the URL of a news or paper, in this sense, it would be very useful to be able to click directly on the metadata and take you to the link.

**Comment by EhuddR** [comment]
I have encountered a bug in the plugin. Apparently if I have empty metadata fields the plugin does not work and does not show the other metadata fields.

https://user-images.githubusercontent.com/78237982/116951817-88f33980-ac4e-11eb-9d55-48114708aee5.mp4

**Comment by arnau** [comment]
Hi @EhuddR, thanks for reporting! Creating links out of URLs is a great idea, thanks :)

As per the bug not showing anything if you have empty metadata fields, it's the same issue that happens with the default behaviour. If I remember correctly it's the Yaml parser failing which might make things a bit more challenging.

I'll give it a go and see if there is a workaround!

**Comment by EhuddR** [comment]
No problem. If the incomplete YAML bug could be fixed, it would be great, since by default in obsidian I can leave those fields incomplete and no error appears. The metadata stills showing up. Of course, the metadata field, by default, is quite limited.

**Comment by arnau** [comment]
You were right. I was conflating the behaviour of hiding the metadata block when no `tags` present with null values in the frontmatter.

Version 0.5.2 fixes null values, lets you define a default value for null values and autolinks URLs.

Thanks!

**Comment by EhuddR** [comment]
Thank you! Now is working flawleslly
