### ISSUE TITLE
[Feature] When Collapse All is opened have all keys be Fully Expanded

### ISSUE THREAD

**Issue by Cantolla** [arnau/obsidian-metatable#20]
Pretty much what it says in the title, I keep my metadata in "Collapse All" state, which is great, but when I click to see my keys they are all collapsed as well, I'd love to have an option to have keys collapsed by default but when opened to be fully expanded.

Thank you! :)

**Comment by arnau** [comment]
Thanks for the suggestion. Sounds like a good option to add 👍

**Comment by arnau** [comment]
@Cantolla, the next non-patch release (i.e. 0.11.0) will provide an option `Collapse root` with this behaviour. Meanwhile, you can test it with the `main` version.
