### ISSUE TITLE
Not Showing invalid metadata

### ISSUE THREAD

**Issue by Archie-2021** [arnau/obsidian-metatable#23]
Core obsidian shows an invalid metadata. I think you should show invalid metadata in red or something to be more obvious not to remove it. It is always bad to happens and user should be alerted

Thanks

**Comment by arnau** [comment]
Thanks @Archie-2021 , could you give me an example?

**Comment by Archie-2021** [comment]
> Thanks @Archie-2021 , could you give me an example?
example of  invalid yaml
![image](https://user-images.githubusercontent.com/85870778/146792390-647ae031-80ac-442d-ab31-cff50887ba53.png)
![image](https://user-images.githubusercontent.com/85870778/146792449-379022a2-93fa-4e52-a6c1-4596b1fc0ffc.png)
example of valid yaml

![image](https://user-images.githubusercontent.com/85870778/146792540-b15755e9-45c7-40ab-84e0-1864762b29a1.png)
![image](https://user-images.githubusercontent.com/85870778/146792589-69125493-98fe-4f1c-90ae-dfe6754b5d9b.png)

**Comment by arnau** [comment]
Thanks @Archie-2021 will take a look 👍

**Comment by Archie-2021** [comment]
> Thanks @Archie-2021 will take a look 👍

I also was thinking that a central note to list all notes with invalid metadata is necessary in vault. maybe you can implement that somewhere in your plugin as it is most related to it. people use quickadd and other means to import notes into their vaults and it happens very often that some character causes an invalid metadata and they may never notice it because it is not going to show up in dataview tables. there is a way to get it for different types of notes in dataview but a central note for all invalid yaml is much more simple and convenient.

and thanks for your great plugin by the way, I should learn more about its CSS functions later.

**Comment by arnau** [comment]
The next version 0.12.0 will show an error message (the same Obsidian provides) when the YAML is invalid.

I've considered the other feature you suggest and I reckon it would be better to have it as an independent plugin given that the logic is not single-document. Maybe something to ask/suggest in the forums?

**Comment by Archie-2021** [comment]
> The next version 0.12.0 will show an error message (the same Obsidian provides) when the YAML is invalid.
> 
> I've considered the other feature you suggest and I reckon it would be better to have it as an independent plugin given that the logic is not single-document. Maybe something to ask/suggest in the forums?

thank you, I will request it on the forum too

**Comment by Archie-2021** [comment]
> The next version 0.12.0 will show an error message (the same Obsidian provides) when the YAML is invalid.
> 
> I've considered the other feature you suggest and I reckon it would be better to have it as an independent plugin given that the logic is not single-document. Maybe something to ask/suggest in the forums?

i can't see this error massage you saying, is it sending a notification (new Notice)? i don't see any massage with or without your plugin. where should i look?

and when this new version is going to be released. it has been a while...

thank you

**Comment by arnau** [comment]
I haven't had spare time to work on this plugin for a while. I can't say when I'll be able to release the next version which contains this fix.

**Comment by Archie-2021** [comment]
> 



> I haven't had spare time to work on this plugin for a while. I can't say when I'll be able to release the next version which contains this fix.

No hurry , what is this built-in obsidian error you were referring to above. can you explain me to me how to get it? it seems useful
