### ISSUE TITLE
can i edit meta-data on live-preview model? and background-image?

### ISSUE THREAD

**Issue by lin0kin** [arnau/obsidian-metatable#24]
in nord theme, metatable is a little hard to identify, I always think of it as part of the text

In addition, I hope to be able to adapt to the new live mode, to be able to directly edit the meatadata

thx

**Comment by arnau** [comment]
hi, I'm not familiar with the nord theme, aren't the options available for customising colours (or the new naked option) enough to make it stand out in your case?

I haven't looked at the new live mode, I'll have to do a bit of research before I can answer this one :)

**Comment by lin0kin** [comment]
> hi, I'm not familiar with the nord theme, aren't the options available for customising colours (or the new naked option) enough to make it stand out in your case?
> 
> I haven't looked at the new live mode, I'll have to do a bit of research before I can answer this one :)

thx bro. it's already amazing plugin.
Thank you for your reply
