### ISSUE TITLE
Inconsistent line height

### ISSUE THREAD

**Issue by jiri** [arnau/obsidian-metatable#28]
Since the tags field shows the tags in a pill shaped container, the overall line height for that row is higher than other lines, resulting in an off-center text.

![image](https://user-images.githubusercontent.com/661524/154617236-a3b631e0-0333-4e11-a335-9328a92db15b.png)

**Comment by arnau** [comment]
Thanks for reporting @jiri

**Comment by arnau** [comment]
@jiri is this still an issue after the revamp of Obsidian 1.0?

**Comment by arnau** [comment]
Closing as Obsidian 1.0 has changed too many things.
