### ISSUE TITLE
Some elements cannot be targeted via CSS

### ISSUE THREAD

**Issue by kepano** [arnau/obsidian-metatable#29]
I couldn't figure out a way to target the `member` element since it doesn't have a `part` — is there another way to do so? I would like to change the `grid-gap` value.

Elements that cannot be targeted:

- `summary` and `marker` for the folding of the main "Metadata" title
- `.set` on the `table` element
- `.member` on the `tr` element

**Comment by arnau** [comment]
Hey @kepano thanks for bringing metatable into the minimal theme. I use your theme myself and I have to say I like your style way more than mine 😄 

Let me look into making more parts available for deeper customisation 👍 

Aside, the `naked` setting removes the shadow dom boundary so styling is completely free. Would this option be more accommodating to you?

**Comment by arnau** [comment]
The new version 0.13.0 adds parts for summary, marker, set and member. It also adds `--metatable-member-gap`
