### ISSUE TITLE
Metatable fails silenty on wrong syntax in frontmatter

### ISSUE THREAD

**Issue by dredhorse** [arnau/obsidian-metatable#31]
Hi,
while obsidan will give you a "Invalid YAML" warning, when you enable Metatable the obisdian warning will not show and Metatable will not create the table without any error message.

You can reproduce this by putting

`title: [this will break yaml] didn't I tell you`

into the frontmatter.

**Comment by arnau** [comment]
Hi @dredhorse thanks, I have a fix but haven't had time to release it yet. Will do as soon as I can.

**Comment by arnau** [comment]
The new version 0.12.0 should fix this.
