### ISSUE TITLE
Feature Request: Cutom link title

### ISSUE THREAD

**Issue by B00tLoad** [arnau/obsidian-metatable#33]
It could be that I'm wrong, but as far as my testing went, it currently is not possible to use a custom link title with the frontmatter links similarly to the wikilinks outside of the frontmatter. It would be very great for readability if it were possible tho.

Example: `%000 index|Index%` would link to the note "000 Index" but the link would only show "Index".

**Comment by arnau** [comment]
The new version 0.13.0 allows you to use the form `[[url|Label]]`.

**Comment by B00tLoad** [comment]
Thanks, but just out of curiosity, is there a technical limitation for the frontmatter links to use the form `%Url|Label%`? As you point out in the readme file, those are way more convenient for your plugin, so it would be cool to be able to use the form there too.

**Comment by arnau** [comment]
Ah, not a technical issue, just a bug :)

**Comment by arnau** [comment]
Version 0.13.1 fixes this case
