### ISSUE TITLE
Chinese Support

### ISSUE THREAD

**Issue by suliveevil** [arnau/obsidian-metatable#36]
When file have two tags：`剧情 喜剧` Metatable treat it as one: `tag:#%E5%89%A7%E6%83%85%20%E5%96%9C%E5%89%A7`

**Comment by arnau** [comment]
@suliveevil thanks for reporting 👍

**Comment by arnau** [comment]
@suliveevil version 0.14.1 fixes this issue

**Comment by suliveevil** [comment]
Thank you very much 🥰

**Comment by Darkluna999** [comment]
now，this problem is still there...
