### ISSUE TITLE
Autolink breaks for wikilinks containing spaces when updating from 13.1 to 14.1

### ISSUE THREAD

**Issue by n-a-m-e** [arnau/obsidian-metatable#37]
Inside the function "Link" urls are encoded and this encoding breaks any wikilinks that contain spaces. For wikilinks the below line setting the localUrl should be the equal to the url variable.

`
const localUrl = encodeURI((0, import_obsidian2.getLinkpath)(url));
`

**Comment by arnau** [comment]
@n-a-m-e thanks for reporting 🙏

**Comment by reddare** [comment]
Confirmed

**Comment by arnau** [comment]
@n-a-m-e this should be fixed with version 0.14.3
