### ISSUE TITLE
[Feature Request] Add an option to not show the metadata

### ISSUE THREAD

**Issue by Mara-Li** [arnau/obsidian-metatable#4]
Hello ! This plugin is great (Looks like a notion frontmatter 👀 ) but sometimes I use the YAML frontmatter to create my cover page (export with pandoc). So, I obviously don't want to show the metadata on the preview! 
It will be great to have an option to not show the metadata. 

Some idea : 
- Add an "exclude files" in the option of the plugin.
- Add a special YAML option (true/false) to not show.
- Add an option to don't show the frontmatter unless you specified with a YAML option or maybe tag... (so, by default, table doesn't appear if you activate this option). 

Thank you for your hard work!

**Comment by arnau** [comment]
Ah! interesting use case. I'll give it a go soon.

**Comment by arnau** [comment]
So I went for a special key in the frontmatter that will skip rendering the table when `true`. By default it is `metatable` but can be configured in the plugin settings.

I also added another setting to define a set of keys that you don't want to be shown.

Both changes can be found in the new 0.5.3 version.

**Comment by dinhngocvuong** [comment]
I always start my note template with metadata, but some quick notes don't need the metadata, and I want to hide the text "Metadata" on preview page when there is nothing to show.

![](https://i.imgur.com/hKRMvC6.png)
