### ISSUE TITLE
Support URLs

### ISSUE THREAD

**Issue by rubasace** [arnau/obsidian-metatable#42]
As the title says, it would be nice to display URLs as clickable links on the metadata table.

I'm using Obsidian to document some software setups and it would be nice to be able to click the URL directly from the metadata table.

**Comment by arnau** [comment]
Hi @rubasace, you can enable the "Autolinks" option which will render URLs as clickable links. You can check the docs here https://github.com/arnau/obsidian-metatable/blob/main/docs/sections/autolinks.md

**Comment by rubasace** [comment]
I see, sorry Arnau, haven't checked this properly
