### ISSUE TITLE
Bad rendering in mobile

### ISSUE THREAD

**Issue by MrModest** [arnau/obsidian-metatable#45]
Hi! I use mobile app (iOS 16.2), app version 1.4.1 (83)

And for some reason the plugin gives me error and renders badly:(

![FAC97A92-8E6C-498D-BB33-078802CC5495](https://user-images.githubusercontent.com/13031058/214833263-6f057117-5bd1-4e83-a481-df384d5284ac.png)

**Comment by MrModest** [comment]
Sorry, I’m stupid. Error related to another plugin. And apparently, once I deleted that plugin, your plugin becomes to render all stuff properly again 😅

But for some reason it missed a field `created`:

![EA4E79F9-AE52-45CA-A730-E739F424A264](https://user-images.githubusercontent.com/13031058/214834059-d6f17a84-4474-4f2d-a757-326bed4cb609.png)
![11A3C287-E841-4335-A3BB-3CFFE9BA7EEA](https://user-images.githubusercontent.com/13031058/214834064-842e4a23-2e7b-4674-b44f-4eabce7367d3.png)

**Comment by MrModest** [comment]
Oh, now. It started to give me wrong render again :(

![213D405C-04CA-4306-985F-1A63B7C6BC9B](https://user-images.githubusercontent.com/13031058/214834772-389642e4-98b8-4eb3-a632-ca4186a2f17a.png)

**Comment by arnau** [comment]
Thanks for reporting @MrModest. I can reproduce the problem 👍

**Comment by ribber** [comment]
I have also encountered this problem, and my device is an Android.

**Comment by LeonardoGentile** [comment]
Same for me, on iOS

**Comment by avinashkanaujiya** [comment]
Hey when can we expect the the fix?, it is kinda proving to be annoying in mobile.

**Comment by arnau** [comment]
No ETA, it highly depends on my free time.

**Comment by arnau** [comment]
Sorry for the long wait. The issue turned out to be a webkit bug. As a result I had to remove the ability to customise the summary. Let me know if the issue persists as I have only been able to test with one iOS phone.
