### ISSUE TITLE
Is it possible to have comma separated values?

### ISSUE THREAD

**Issue by ThornedRose** [arnau/obsidian-metatable#49]
Apologies if this is answered in the documentation - I have Cognitive Impairment so, despite reading through all the documentation, I may have missed it.

If, for example, I have the Aliases key in my YAML, currently all values show as a single string with spaces between each value:

`aliases: all values run together`

When I would like them to look like

`aliases: all, values, dont, run, together`

I've tried looking at the CSS myself but since it's outputs as `<span class="leaf string" part="leaf string">all values run together</span>`, I can't target each individual value.

Thanks!

**Comment by arnau** [comment]
Hi @ThornedRose it is not possible right now. If you want `aliases` to behave like a list, you should use a YAML array:

```yaml
aliases: [alpha, beta, gamma]
```

That said, right now this plugin treats the `tags` key as a special case to mimic the original Obsidian behaviour. On that basis, it should mimic the behaviour for `aliases` which means that the following should work:

```yaml
aliases: alpha, beta, gamma
```

I'll keep this issue open as a reminder that this needs to be done. Thanks!

**Comment by arnau** [comment]
Version 0.14.5 handles the `aliases` key as a special case.

**Comment by arnau** [comment]
Correct, different funny symbol than the default in Obsidian (which I don't like 😄 ). You can change it (or remove it entirely) if you change the CSS property `  --metatable-alias-symbol` in a custom [CSS Snippet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets)

**Comment by arnau** [comment]
The following should work:

```css
 .obsidian-metatable,
.obsidian-metatable-sidebar {
  --metatable-alias-symbol: "";
}
```

**Comment by arnau** [comment]
The only way would be to switch to nacked mode and bring your CSS.
