### ISSUE TITLE
eating zeros of number in metatable

### ISSUE THREAD

**Issue by tyePhDCandy** [arnau/obsidian-metatable#50]
# eating leading zeros of number in metatable
screen shot : the number `32` should have been `000032`
![image](https://user-images.githubusercontent.com/22343659/230160062-d13fdc38-eb42-48ca-8ad5-32cce2401b62.png)

**Comment by arnau** [comment]
Hi @tyePhDCandy I'm afraid this is expected. Metatable uses the frontmatter [YAML](https://yaml.org/spec/1.2.2/) which treats unquoted numeric values as numbers. If you need to represent digits such as `000032` you'll need to use strings which effectively means one of the following:

```yaml
code: "000032"
aliases: ['000032']
```
