### ISSUE TITLE
Bug: The plugin doesn't work whitout quotation marks on numbers.

### ISSUE THREAD

**Issue by EhuddR** [arnau/obsidian-metatable#6]
Hi! I woul like to report that the plugin isn't working. 
This is the console error:

![image](https://user-images.githubusercontent.com/78237982/117590499-60a78700-b0f5-11eb-8822-6a5940934c7e.png)

So, I play around whit it and found that the plugin doesn't show numeric values whithin the frontmatter i.e:

```---
aliases: [ ]
tags: literature
author: Chomsky
year: 2020
URL: https://www.something.com
page: 123
---
```

The plugin works whit the frontmatter like so though:

```---
aliases: [ ]
tags: literature
author: Chomsky
year: "2020"
URL: https://www.something.com
page: "123"
---
```

The numeric values are rendered correctly when you put them around `""` or `''`. 

In this sense, I like to ask if you can make readable those values whitout the quatation marks?

And thanks in advance.

**Comment by arnau** [comment]
Thanks for reporting. Sorry for the regression. It should work in 0.7.1
