### ISSUE TITLE
Too small width for key in mobile version (in portrait mode)

### ISSUE THREAD

**Issue by MrModest** [arnau/obsidian-metatable#8]
My Phone: 
OnePlus 7
Android 11
Display: 6.41" 1920x1080 (FullHD)

Keys badly cut in Portrait mode. Please can you fix it?

Examples on screenshot: `aliases`, and `long_member`

First bad because of icon. Second bad because of length of field key.

Portrait mode:

![image](https://user-images.githubusercontent.com/13031058/119797349-d1ff7c00-bee2-11eb-9ad8-0b7e699622a4.png)

Landscape mode:

![image](https://user-images.githubusercontent.com/13031058/119797406-e04d9800-bee2-11eb-8574-977c00b50e51.png)

**Comment by arnau** [comment]
Thanks for reporting! Looks to me that it should be displayed perhaps a bit differently to give enough room for long keys and long values?

I don't use Obsidian on mobile so I'd be keen to get your thoughts on what would be a convenient way to display the information

**Comment by MrModest** [comment]
![image](https://user-images.githubusercontent.com/13031058/119864185-0f83f980-bf23-11eb-8cfc-bf3eee6b25b9.png)

this is how it's look in default. 

I think your table format is good, but it need to more max-width limit, I guess

Also I think, max-limit need to be a bit increased if we have expand button

**Comment by arnau** [comment]
Ook, I'll work with that :) give me a couple of days

**Comment by arnau** [comment]
After a few tests I settled with a vertical layout for small screens, otherwise values don't have enough space. You'll see the change in 0.9.1

**Comment by MrModest** [comment]
Actually, it's not so bad. Thank you! (:

![image](https://user-images.githubusercontent.com/13031058/120104915-7857b580-c15f-11eb-9e93-8e19652934fc.png)

![image](https://user-images.githubusercontent.com/13031058/120104926-80175a00-c15f-11eb-872c-d58e334890f7.png)
